# Generated by Django 2.2.6 on 2019-12-28 09:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='BlogTopic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='instructor',
            field=models.CharField(default=datetime.datetime(2019, 12, 28, 9, 52, 40, 644671, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
