# Generated by Django 2.2.6 on 2019-12-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0002_auto_20191228_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='instructor',
            new_name='topic',
        ),
    ]
