# Generated by Django 2.2.6 on 2019-12-29 08:08

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0005_auto_20191228_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(help_text='ignore Message From Froala'),
        ),
    ]
