# Generated by Django 2.2.6 on 2019-12-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0008_auto_20191231_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Fun', 'Fun'), ('Knowledge', 'Knowledge'), ('Science', 'Science')], default='Knowledge', max_length=50),
        ),
    ]
