# Generated by Django 2.2.6 on 2019-12-22 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_auto_20191221_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='\\profile_pics'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(null=True, upload_to='profile_pics', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])]),
        ),
    ]
