# Generated by Django 2.2.6 on 2020-01-13 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrcoder_title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('mrcoder_description', models.CharField(max_length=300)),
                ('mrcoder_created_at', models.DateTimeField(auto_now_add=True)),
                ('mrcoder_updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='basicmrcoderwhite.Category_Choice')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrcoder_title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('mrcoder_content', martor.models.MartorField(null=True)),
                ('mrcoder_created_at', models.DateTimeField(auto_now_add=True)),
                ('mrcoder_updated_at', models.DateTimeField(auto_now=True)),
                ('mrcoder_solved', models.BooleanField(default=False)),
                ('mrcoder_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrcoder_question', to='basicmrcoderwhite.Category_Choice')),
                ('mrcoder_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mrcoder_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
