# Generated by Django 2.2.6 on 2019-12-14 14:52

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
