# Generated by Django 2.2.6 on 2019-12-15 14:41

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_auto_20191215_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
