# Generated by Django 2.2.6 on 2019-12-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0006_auto_20191215_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
