# Generated by Django 2.2.6 on 2019-12-16 07:12

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=100)),
                ('descriptions', froala_editor.fields.FroalaField()),
                ('is_active', models.BooleanField(default=False)),
                ('course_link', models.CharField(max_length=300)),
                ('promo_code', models.CharField(max_length=50)),
            ],
        ),
    ]
