# Generated by Django 2.2.6 on 2019-12-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freecourses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_slug', models.SlugField(help_text='Unique Value For Product Page Url,Created From Name.', unique=True)),
                ('course_description', models.TextField()),
                ('course_is_active', models.BooleanField(default=True)),
                ('course_meta_keywords', models.CharField(help_text='comma-delimited set of SEO keywords for meta Tag', max_length=255, verbose_name='Meta Keywords')),
                ('course_created_at', models.DateTimeField(auto_now_add=True)),
                ('course_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.ManyToManyField(to='freecourses.Course_Category'),
        ),
    ]
