# Generated by Django 2.2.6 on 2019-12-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freecourses', '0002_auto_20191216_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='category',
        ),
    ]
