# Generated by Django 2.2.6 on 2019-12-16 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('freecourses', '0003_remove_courses_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_category',
            name='course_created_at',
        ),
        migrations.RemoveField(
            model_name='course_category',
            name='course_meta_keywords',
        ),
        migrations.RemoveField(
            model_name='course_category',
            name='course_updated_at',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 12, 16, 13, 36, 28, 681682, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='course_meta_keywords',
            field=models.CharField(default=datetime.datetime(2019, 12, 16, 13, 36, 44, 519917, tzinfo=utc), help_text='comma-delimited set of SEO keywords for meta Tag', max_length=255, verbose_name='Meta Keywords'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='course_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
