# Generated by Django 2.2.6 on 2019-12-31 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('duplicated', 'Duplicated'), ('pending', 'Pending'), ('on_hold', 'On Hold'), ('closed', 'Closed'), ('deleted', 'Deleted')], default='approved', max_length=20, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('edited', models.BooleanField(default=False, verbose_name='Edited?')),
            ],
            options={
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('wiki', models.TextField(blank=True, null=True, verbose_name='Wiki')),
                ('edited', models.BooleanField(default=False, verbose_name='Edited?')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_creator', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'tags',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSuggestedEdits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('comment', models.TextField(verbose_name='Revision Comment')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_edits_editor', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_edits_question', to='coder.Question')),
                ('tags', models.ManyToManyField(related_name='suggested_edits_tags', to='coder.Tag')),
            ],
            options={
                'verbose_name_plural': 'question suggested edits',
                'ordering': ['-created'],
            },
        ),
    ]
